"use client";

import Head from "next/head";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { createClient } from "@/lib/supabase/client";
import { useSessionContext } from "@/lib/use-session-context";

type Plan = { id: string; code: string; name: string; description: string | null; monthly_price_php: number; campaign_limit: number; monthly_click_limit: number; hotspot_limit: number };
type Subscription = { id: string; status: string; billing_interval: string; current_period_end: string | null; cancel_at_period_end: boolean; provider: string; plan: { name: string; code: string } | null };
type Payment = { id: string; amount_php: number; status: string; created_at: string; gcash_reference_number: string | null };

export default function BillingPage() {
  const { loading, profile, error } = useSessionContext(); const [plans, setPlans] = useState<Plan[]>([]); const [subscription, setSubscription] = useState<Subscription | null>(null); const [payments, setPayments] = useState<Payment[]>([]); const [dataError, setDataError] = useState("");
  useEffect(() => { if (!profile) return; const supabase = createClient(); Promise.all([supabase.from("plans").select("id, code, name, description, monthly_price_php, campaign_limit, monthly_click_limit, hotspot_limit").eq("is_active", true).eq("is_public", true).order("monthly_price_php"), supabase.from("subscriptions").select("id, status, billing_interval, current_period_end, cancel_at_period_end, provider, plan:plans(name, code)").eq("user_id", profile.id).order("created_at", { ascending: false }).limit(1).maybeSingle(), supabase.from("payments").select("id, amount_php, status, created_at, gcash_reference_number").eq("user_id", profile.id).order("created_at", { ascending: false }).limit(20)]).then(([planResult, subscriptionResult, paymentResult]) => { if (planResult.error || subscriptionResult.error || paymentResult.error) setDataError(planResult.error?.message || subscriptionResult.error?.message || paymentResult.error?.message || "Unable to load billing data."); setPlans((planResult.data ?? []) as Plan[]); setSubscription(subscriptionResult.data as unknown as Subscription | null); setPayments((paymentResult.data ?? []) as Payment[]); }); }, [profile]);
  if (error || dataError) return <div className="app-shell"><div className="app-main"><section className="app-card"><h2>Unable to load billing</h2><p className="muted">{error || dataError}</p></section></div></div>;
  if (loading || !profile) return <div className="app-shell"><div className="app-main"><div className="skeleton-stats"><div className="skeleton" /><div className="skeleton" /><div className="skeleton" /></div></div></div>;
  return <><Head><title>Billing | Afflio</title></Head><AppShell area="dashboard" profile={profile} subtitle="Your plan, limits, renewal state, and transaction history." title="Billing"><section className="app-grid app-grid--two"><article className="app-card"><p className="app-topbar__eyebrow">Current subscription</p><h2>{subscription?.plan?.name || "Free"}</h2><div className="data-list"><div className="data-list__row"><span className="muted">Status</span><span className={`badge badge--${subscription?.status === "active" ? "active" : "draft"}`}>{subscription?.status || "free"}</span></div><div className="data-list__row"><span className="muted">Provider</span><strong>{subscription?.provider || "None"}</strong></div><div className="data-list__row"><span className="muted">Current period ends</span><strong>{subscription?.current_period_end ? new Date(subscription.current_period_end).toLocaleDateString() : "No renewal"}</strong></div></div></article><article className="app-card"><p className="app-topbar__eyebrow">Checkout status</p><h2>Payments are being configured</h2><p className="muted">Plan upgrades will become available after the production payment provider and signed webhook are connected.</p></article></section><section className="app-card"><div className="section-head"><div><p className="app-topbar__eyebrow">Plans</p><h2>Choose the capacity you need</h2></div></div><div className="billing-plan-grid">{plans.map((plan) => <article className="billing-plan" key={plan.id}><div><span className="badge badge--active">{plan.code}</span><h3>{plan.name}</h3><p className="muted">{plan.description}</p></div><strong className="billing-plan__price">{plan.monthly_price_php ? `PHP ${plan.monthly_price_php}/mo` : "Free"}</strong><ul><li>{plan.campaign_limit} campaigns</li><li>{plan.monthly_click_limit.toLocaleString()} monthly clicks</li><li>{plan.hotspot_limit} hotspots per campaign</li></ul><button className="btn btn-outline" disabled type="button">Checkout coming soon</button></article>)}</div></section><section className="app-card"><div className="section-head"><div><p className="app-topbar__eyebrow">Payment history</p><h2>Transactions</h2></div></div>{payments.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Date</th><th>Amount</th><th>Status</th><th>Reference</th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id}><td>{new Date(payment.created_at).toLocaleDateString()}</td><td>PHP {payment.amount_php}</td><td><span className={`badge badge--${payment.status === "approved" ? "active" : "draft"}`}>{payment.status}</span></td><td>{payment.gcash_reference_number || "-"}</td></tr>)}</tbody></table></div> : <div className="empty-state"><h3>No payments yet</h3><p>Your completed and pending payments will appear here.</p></div>}</section></AppShell></>;
}
